{
 "title": "Bor-Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "bor" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_sysload", "legendFormat": "system" },
    { "expr": "system_cpu_syswait", "legendFormat": "iowait" },
    { "expr": "system_cpu_procload", "legendFormat": "geth" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(system_memory_allocs[1m])", "legendFormat": "alloc" },
    { "expr": "system_memory_used", "legendFormat": "used" },
    { "expr": "system_memory_held", "legendFormat": "held" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes[1m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(p2p_ingress[1m])", "legendFormat": "ingress" },
    { "expr": "rate(p2p_egress[1m])", "legendFormat": "egress" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "peers" },
    { "expr": "rate(p2p_dials[1m])", "legendFormat": "dials" },
    { "expr": "rate(p2p_serves[1m])", "legendFormat": "serves" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latest header",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_header" }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chain_head_header", "legendFormat": "header" },
    { "expr": "chain_head_receipt", "legendFormat": "receipt" },
    { "expr": "chain_head_block", "legendFormat": "block" }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_pending" }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "executable" },
    { "expr": "txpool_queued", "legendFormat": "gapped" },
    { "expr": "txpool_local", "legendFormat": "local" }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_receipt" }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_queued" }
   ]
  },
  {
   "title": "Latest block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  {
   "title": "Local transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_local" }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(txpool_valid[1m])", "legendFormat": "valid" },
    { "expr": "rate(txpool_invalid[1m])", "legendFormat": "invalid" },
    { "expr": "rate(txpool_underpriced[1m])", "legendFormat": "underpriced" },
    {
     "expr": "rate(txpool_pending_discard[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_read", "legendFormat": "leveldb read" },
    { "expr": "eth_db_chaindata_disk_write", "legendFormat": "leveldb write" },
    { "expr": "eth_db_chaindata_ancient_read", "legendFormat": "ancient read" },
    { "expr": "eth_db_chaindata_ancient_write", "legendFormat": "ancient write" }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "leveldb" },
    { "expr": "eth_db_chaindata_ancient_size", "legendFormat": "ancient" }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_write[1m])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}